import { ReportType, ExportFormat } from '@prisma/client'
import type { ServiceResult } from '@/types'
import { generatePdf } from './pdf.service'
import { generateExcel } from './excel.service'
import { sendReportEmail } from './email.service'
import { format } from 'date-fns'
import { prisma } from '@/lib/db'

interface GenerateReportInput {
  generated_by: string
  report_type: 'Daily' | 'Weekly' | 'Monthly' | 'Custom'
  company_name: string
  date_from: Date
  date_to: Date
  export_format: 'PDF' | 'Excel'
  recipient_email?: string
}

interface GenerateReportOutput {
  report_id: string
  buffer: Buffer
  contentType: string
  filename: string
  emailed: boolean
}

export async function generate(input: GenerateReportInput): Promise<ServiceResult<GenerateReportOutput>> {
  try {
    const patients = await prisma.patientRecord.findMany({
      where: {
        company_name: input.company_name,
        created_at: { gte: input.date_from, lte: input.date_to },
      },
      include: { medic: { select: { full_name: true } } },
    })

    const totalPatients = patients.length

    const medicMap: Record<string, number> = {}
    patients.forEach((p) => {
      medicMap[p.attending_medic_id] = (medicMap[p.attending_medic_id] || 0) + 1
    })
    const medicBreakdown = Object.entries(medicMap).map(([medic_id, patients_seen]) => ({
      medic_id,
      patients_seen,
    }))

    // Aggregate drug usage
    const drugMap: Record<string, { drug_name: string; quantity_dispensed: number; unit: string }> = {}
    patients.forEach((p) => {
      const drugs = (p.drugs_dispensed ?? []) as { drug_name: string; quantity_dispensed: number; unit?: string }[]
      drugs.forEach((d) => {
        if (drugMap[d.drug_name]) {
          drugMap[d.drug_name].quantity_dispensed += d.quantity_dispensed
        } else {
          drugMap[d.drug_name] = {
            drug_name: d.drug_name,
            quantity_dispensed: d.quantity_dispensed,
            unit: d.unit || 'units',
          }
        }
      })
    })
    const totalDrugsUsed = Object.values(drugMap)

    const patientRows = patients.map((p) => ({
      full_name: p.full_name,
      staff_code: p.staff_code,
      department: p.department,
      date_of_visit: format(p.date_of_visit, 'dd/MM/yyyy'),
      diagnosis: p.diagnosis,
      treatment: p.treatment,
    }))

    const reportData = {
      company_name: input.company_name,
      report_type: input.report_type,
      date_from: input.date_from,
      date_to: input.date_to,
      total_patients_seen: totalPatients,
      total_drugs_used: totalDrugsUsed,
      medic_breakdown: medicBreakdown,
      patients: patientRows,
    }

    let buffer: Buffer
    let contentType: string
    let extension: string

    if (input.export_format === 'PDF') {
      buffer = await generatePdf(reportData)
      contentType = 'application/pdf'
      extension = 'pdf'
    } else {
      buffer = await generateExcel(reportData)
      contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      extension = 'xlsx'
    }

    const filename = `SiteCheck_${input.report_type}_${format(input.date_from, 'yyyyMMdd')}-${format(input.date_to, 'yyyyMMdd')}.${extension}`

    const report = await prisma.report.create({
      data: {
        generated_by: input.generated_by,
        report_type: input.report_type as ReportType,
        date_from: input.date_from,
        date_to: input.date_to,
        company_name: input.company_name,
        total_patients_seen: totalPatients,
        total_drugs_used: totalDrugsUsed,
        medic_breakdown: medicBreakdown,
        export_format: input.export_format as ExportFormat,
        sent_via_email: !!input.recipient_email,
        recipient_email: input.recipient_email,
        status: 'Pending',
      },
    })

    let emailed = false
    if (input.recipient_email) {
      const emailResult = await sendReportEmail({
        to: input.recipient_email,
        subject: `SiteCheck ${input.report_type} Report - ${input.company_name}`,
        text: [
          `Hi,`,
          ``,
          `Please find attached the ${input.report_type.toLowerCase()} report for ${input.company_name}.`,
          `Period: ${format(input.date_from, 'dd/MM/yyyy')} - ${format(input.date_to, 'dd/MM/yyyy')}`,
          `Total patients seen: ${totalPatients}`,
          ``,
          `Generated by SiteCheck`,
          `This is an automated message. Please do not reply.`,
        ].join('\n'),
        attachments: [{ filename, content: buffer, contentType }],
      })

      emailed = emailResult.success
      await prisma.report.update({
        where: { report_id: report.report_id },
        data: { status: emailed ? 'Sent' : 'Failed', sent_via_email: true },
      })
    }

    return {
      success: true,
      data: { report_id: report.report_id, buffer, contentType, filename, emailed },
    }
  } catch (err) {
    console.error('[ReportService]', err instanceof Error ? err.message : err)
    return { success: false, error: 'Could not generate report.', code: 'REPORT_GENERATE_FAILED' }
  }
}

export async function listByCompany(company_name: string): Promise<ServiceResult<unknown[]>> {
  try {
    const reports = await prisma.report.findMany({
      where: { company_name },
      orderBy: { created_at: 'desc' },
      include: { generator: { select: { full_name: true } } },
    })
    return { success: true, data: reports }
  } catch {
    return { success: false, error: 'Could not fetch reports.', code: 'REPORT_LIST_FAILED' }
  }
}
